apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: bank-of-anthos
requires:
- configs:
  - accounts
  path: src/accounts/skaffold.yaml
- configs:
  - ledger
  path: src/ledger/skaffold.yaml
- configs:
  - frontend
  path: src/frontend/skaffold.yaml
- configs:
  - loadgenerator
  path: src/loadgenerator/skaffold.yaml
- configs:
  - accounts-db
  path: src/accounts/accounts-db/skaffold.yaml
- configs:
  - ledger-db
  path: src/ledger/ledger-db/skaffold.yaml
deploy:
  tolerateFailuresUntilDeadline: true
